import React from 'react';
import { StyleSheet, Dimensions } from 'react-native';

const {width: WIDTH } = Dimensions.get('window')

const styles = StyleSheet.create({
	boxFriendOptions: {
		borderWidth: 1,
		borderColor: '#999',
		padding: 10,
	},
	bottomBar: {
		flexDirection: 'row',
		alignItems: 'center',
		padding: 5,
		position: 'absolute',
		bottom: 0,
		left: 0,
		right: 0,
		zIndex: 2,
		height: 60,
	},
	btnLogIn: {
		fontSize: 18,
		color: 'white',
		backgroundColor: '#dc3545',
		padding: 10,
		paddingLeft: 20,
		paddingRight: 20,
		width: '80%',
		borderRadius: 100,
		margin: 5,
	},
	profile: {
		backgroundColor: '#fff',
		paddingHorizontal: 10
	},
	btnChange: {
		fontSize: 16,
		color: '#000',
		backgroundColor: '#cccccc3b',
		padding: 10,
		borderRadius: 3,
		margin: 5,
	},
	btnLogOut: {
		// size: '40%',
		fontSize: 16,
		color: '#000',
		backgroundColor: '#dc3545',
		padding: 10,
		borderRadius: 3,
		margin: 5,
	},
	btnRegister: {
		fontSize: 18,
		color: 'white',
		backgroundColor: '#28a745',
		padding: 10,
		borderRadius: 100,
		margin: 5,
		paddingLeft: 20,
		paddingRight: 20,
	},
	btnText: {
		color: 'darkblue',
		fontSize: 17,
		marginTop: 10,
	},
	container: {
		flex: 1,
		backgroundColor: '#fff',
		alignItems: 'center',
		justifyContent: 'center',
	},
	containerFriendScreen: {
		marginTop: 10
	},
	friendScreenIcon: {
		width: 25,
		height: 25,
		position: 'relative',
		resizeMode: 'cover',
		tintColor: '#3f51b5',
		alignSelf: 'center',
	},
	friendScreenText: {
		fontSize: 17,
		color: '#000',
		backgroundColor: '#ccc',
		padding: 10,
		borderRadius: 3,
		margin: 5,
	},
	iconLeft: {
		position: 'absolute',
		left: 15,
		top: 15,
		color: '#3f51b5',
	},
	iconRight: {
		position: 'absolute',
		right: 15,
		top: 15,
		color: '#808080',
	},
	iconInputText: {
		height: 30,
		width: 30,
		tintColor: '#222',
		marginRight: 5,
		marginBottom: 6,
	},
	input: {
		padding: 10,
		borderWidth: 1,
		borderColor: '#ccc',
		width: '100%',
		marginBottom: 10,
		borderRadius: 100,
		fontSize: 17,
		paddingLeft: 50,
	},
	inputMessage: {
		padding: 10,
		borderWidth: 1,
		borderColor: '#ccc',
		width: '60%',
		marginBottom: 10,
		borderRadius: 20,
	},
	inputSearch: {
		marginTop: 10,
		marginBottom: 10,
		marginLeft: '5%',
		padding: 8,
		borderWidth: 1,
		borderColor: '#ccc',
		width: '90%',
		borderRadius: 40,
	},
	sendButton: {
		alignItems: 'center',
		marginBottom: 10,
		marginLeft: 10,
		height: 40,
		width: 40,
		paddingTop: 10,
		paddingLeft: 5,
		backgroundColor: '#2196F3',
		borderRadius: 20,
	},
	inputContainer: {
		borderBottomColor: '#F5FCFF',
		backgroundColor: '#FFFFFF',
		borderRadius: 30,
		borderBottomWidth: 1,
		width: 250,
		height: 45,
		marginBottom: 20,
		flexDirection: 'row',
		alignItems: 'center',
	},
});
export default styles;
